# Generated by Django 5.2.7 on 2025-11-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFolder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('folder_name', models.CharField(max_length=255)),
                ('folder_id', models.CharField(max_length=100, unique=True)),
                ('lname', models.CharField(max_length=100, verbose_name='Last Name')),
                ('fname', models.CharField(max_length=100, verbose_name='First Name')),
                ('midname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Middle Name')),
                ('full_name', models.CharField(editable=False, max_length=255)),
            ],
            options={
                'db_table': 'student_folders',
                'ordering': ['lname', 'fname'],
            },
        ),
    ]
