# Generated by Django 5.2.6 on 2025-11-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0003_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='max_size',
            field=models.IntegerField(),
        ),
    ]
