# Generated by Django 5.2.6 on 2025-11-05 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0005_program_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_lab_unit',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_lec_unit',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='program',
        ),
        migrations.AddField(
            model_name='course',
            name='course_title',
            field=models.CharField(default='No Title', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='lab_units',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='lec_units',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='semester_offered',
            field=models.CharField(default='Not Specified', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='year_level',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('effective_semester', models.CharField(max_length=20)),
                ('effective_year', models.IntegerField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='registrar.program')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='curriculum',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='registrar.curriculum'),
        ),
        migrations.AddField(
            model_name='student',
            name='curriculum',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='registrar.curriculum'),
        ),
    ]
