# Generated by Django 5.2.6 on 2025-11-05 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0006_remove_course_course_lab_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='effective_semester',
        ),
        migrations.RemoveField(
            model_name='program',
            name='description',
        ),
    ]
