# Generated by Django 5.2.6 on 2025-11-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0007_remove_curriculum_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='program_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
