# Generated by Django 5.2.6 on 2025-11-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0008_alter_program_program_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='major',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
