# Generated by Django 5.2.6 on 2025-11-05 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0009_curriculum_major'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='effective_year',
        ),
    ]
