# Generated by Django 5.2.6 on 2025-11-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0010_remove_curriculum_effective_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_abbreviation',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
