# Generated by Django 5.2.6 on 2025-11-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0011_program_program_abbreviation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100)),
                ('semester', models.TextField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_code', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('units', models.IntegerField(default=0)),
                ('file_source', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
