# Generated by Django 5.2.6 on 2025-11-14 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0012_promotionalreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotionalreport',
            old_name='file_source',
            new_name='source_file',
        ),
    ]
