# Generated by Django 5.2.6 on 2025-11-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0014_folder_folder_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100, unique=True)),
                ('button_label', models.CharField(default='N/A', max_length=50)),
                ('button_class', models.CharField(default='N/A', max_length=50)),
            ],
        ),
    ]
