# Generated by Django 5.2.6 on 2025-11-15 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('registrar', '0015_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_label', models.CharField(max_length=50)),
                ('button_class', models.CharField(max_length=50)),
                ('permission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
            ],
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
