# Generated by Django 5.2.6 on 2025-11-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0016_extendedpermission_delete_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedpermission',
            name='button_icon',
            field=models.CharField(default='<span class="badge bg-secondary">4</span>', max_length=50),
        ),
    ]
